### ISSUE TITLE
How to Enable Profiling in Kubernetes Pods?

### ISSUE THREAD

**Issue by ddaaac** [async-profiler/async-profiler#937]
I read the section on [profiling in a container](https://github.com/async-profiler/async-profiler?tab=readme-ov-file#profiling-java-in-a-container). I have an application running on Kubernetes pods. So instead of `docker run --security-opt seccomp=unconfined --cap-add SYS_ADMIN`, I tried the following:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
  template:
    spec:
      containers:
        - name: deployment-name
          securityContext:
            capabilities:
              add: [ "SYS_ADMIN" ]
            seccompProfile:
              type: Unconfined
```

But I'm still encountering this error: `[ERROR] No access to perf events. Try --fdtransfer or --all-user option or 'sysctl kernel.perf_event_paranoid=1'`.
How can I profile my application in Kubernetes pods?
